=== Parsa-P3/JS-HTML/xml/servidorxsd.xsd
<?xml version="1.0"?>
<!-- Alternativa en XML para validar nuestros XMLs   -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="configuracion_servidor">
        <xsd:complexType>
            <xsd:sequence>
            
                <xsd:element name="base_datos" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="usuario" type="xsd:string"></xsd:element>
                            <xsd:element name="contrasena" type="xsd:string"></xsd:element>
                            <xsd:element name="puerto">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:int">
                                        <xsd:minInclusive value="1024"></xsd:minInclusive>
                                        <xsd:maxExclusive value="65535"></xsd:maxExclusive>
                                    </xsd:restriction>
                                </xsd:simpleType>
                             </xsd:element>
                             <xsd:element name="maximo_conexion" type="xsd:int"></xsd:element>
                             <xsd:element name="modo_acceso">
                                    <xsd:simpleType>
                                        <xsd:restriction base="xsd:string">
                                            <xsd:enumeration value="local"></xsd:enumeration>
                                            <xsd:enumeration value="remoto"></xsd:enumeration>
                                        </xsd:restriction>
                                    </xsd:simpleType>
                             </xsd:element>
                        </xsd:sequence> 
                        <xsd:attribute name="nombre" type="xsd:string"></xsd:attribute>                            
                     </xsd:complexType>
                </xsd:element>

                <xsd:element name="backups">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ruta" type="xsd:string"></xsd:element>
                            <xsd:element name="frecuencia" >
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="diaria"></xsd:enumeration>
                                        <xsd:enumeration value="semanal"></xsd:enumeration>
                                        <xsd:enumeration value="mensual"></xsd:enumeration>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Parsa-P3/JS-HTML/xml/servidor.xml
<?xml version="1.0" encoding="UTF-8"?>


<configuracion_servidor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="servidorxsd.xsd">
<!-- configuracion para la base de datos de pruebas -->
    <base_datos nombre="BD_Pruebas">
      <usuario>admin</usuario>
      <!-- validacion para contrasena es con CDATA -->
      <contrasena> <![CDATA[1234]]>
      </contrasena>
      <puerto>1024</puerto>
      <maximo_conexion>100</maximo_conexion>
      <modo_acceso>local</modo_acceso>
    </base_datos>
    

    <base_datos nombre="BD_Produccion">
      <usuario>admin</usuario>
      <contrasena> <![CDATA[1234]]>
      </contrasena>
      <puerto>1025</puerto>
      <maximo_conexion>100</maximo_conexion>
      <modo_acceso>local</modo_acceso>
    </base_datos>

    <backups>
            <ruta>/var/logs/backup</ruta>
            <frecuencia>semanal</frecuencia>
    </backups>
</configuracion_servidor>
